### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by wxbool** [yvonwin/qwen2.cpp#1]
Can it be compiled on windows?

**Comment by yvonwin** [comment]
I can't do it now, but I will add support later when I have time.

**Comment by yvonwin** [comment]
Hello, I have made some modifications to support building on Windows. @wxbool 
![Xnip2024-04-11_09-36-58](https://github.com/yvonwin/qwen2.cpp/assets/15075080/07bed427-4133-4a72-84c6-9212ca1c7664)
