### ISSUE TITLE
Is there a converted ggml file for sharing?

### ISSUE THREAD

**Issue by zhouxihong1** [yvonwin/qwen2.cpp#2]
Model conversion requires cloning the original model, 
but it takes a lot of time to download. 

I would like to ask the author if he has a converted model to share.

**Comment by yvonwin** [comment]
Greetings, my attempt to upload to Kaggle has proven to be somewhat sluggish. Perhaps it would be beneficial for you to execute a test conversion with smaller file sizes like 0.5b, 1.8b, or 4b on Colab.

**Comment by zhouxihong1** [comment]
I have used colab to convert the 14b and 7b models, and compiled qwen2.cpp on Windows. After q4_0 quantization, it can output normally; the speed is much faster than llama, but the accuracy seems to be weaker than llama.cpp, not yet I understand the principle, but the review shows that it has become weaker.


中文翻译：
我已经用colab转换了14b和7b模型，并且在Windows上编译了qwen2.cpp，经过q4_0量化后，能够正常输出；速度比llama要快很多，但好像精度比llama.cpp要弱一些，暂不清楚原理，但评测来看是变弱了

**Comment by yvonwin** [comment]
模型的速度可能和优化有关心，精度应该是一样的。如果要弱一些，可能是默认量化类型的原因，可以参考以下的量化精度。
Old quant types (some base model types require these):
- Q4_0: small, very high quality loss - legacy, prefer using Q3_K_M
- Q4_1: small, substantial quality loss - legacy, prefer using Q3_K_L
- Q5_0: medium, balanced quality - legacy, prefer using Q4_K_M
- Q5_1: medium, low quality loss - legacy, prefer using Q5_K_M

New quant types (recommended):
- Q2_K: smallest, extreme quality loss - not recommended
- Q3_K: alias for Q3_K_M
- Q3_K_S: very small, very high quality loss
- Q3_K_M: very small, very high quality loss
- Q3_K_L: small, substantial quality loss
- Q4_K: alias for Q4_K_M
- Q4_K_S: small, significant quality loss
- Q4_K_M: medium, balanced quality - recommended
- Q5_K: alias for Q5_K_M
- Q5_K_S: large, low quality loss - recommended
- Q5_K_M: large, very low quality loss - recommended
- Q6_K: very large, extremely low quality loss
- Q8_0: very large, extremely low quality loss - not recommended
- F16: extremely large, virtually no quality loss - not recommended
- F32: absolutely huge, lossless - not recommended

**Comment by zhouxihong1** [comment]
好的，我改天再试下新的转换方式

**Comment by zhouxihong1** [comment]
新的转换方式好像不能通过qwen2提供的脚本完成转换，还是只能用Q4_0  Q5_1之类的方式

**Comment by yvonwin** [comment]
抱歉，我指的是llamacpp更新后量化的方式的差异，由于时间原因，我没有跟进这个。我是指应该对比同等的量化精度的性能。

**Comment by zhouxihong1** [comment]
哦哦，好的；那就是正常的了，感谢；吞吐率qwen2.cpp 比 llama.cpp的好很多
