### ISSUE TITLE
gpu版本为啥无法使用

### ISSUE THREAD

**Issue by bai1451746927** [yvonwin/qwen2.cpp#3]
gpu版本会报错：
ggml_aligned_malloc: insufficient memory (attempted to allocate 876546.56 MB)
GGML_ASSERT: /tmp/pip-req-build-5898jsey/third_party/ggml/src/ggml.c:2327: ctx->mem_buffer != NULL
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: 不允许的操作.
No stack.
The program is not being run.
已放弃 (核心已转储)
请问是哪里导致的memory过载？

**Comment by yvonwin** [comment]
能否告诉你运行的模型和平台环境？

**Comment by bai1451746927** [comment]
已解决，怀疑是初次使用的问题，过了一段时间之后该问题消失了
