### ISSUE TITLE
如何找到或生成Qwen2-7B-Instruct-q8.ggml需要的qwen.tiktoken？

### ISSUE THREAD

**Issue by virtual1126** [yvonwin/qwen2.cpp#6]
附带的qwen.tiktoken报错：                
$ ./build/bin/main -m Qwen2-7B-Instruct-q8.ggml  -p 你想活出怎样的人生 -s "你是一个猫娘"                                                                       
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no                                                                                                                                                                 
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes                                                                                                                                                                
ggml_init_cublas: found 1 CUDA devices:                                                                                                                                                                     
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes                                                                                                                                       
unknown token: 152063

**Comment by yvonwin** [comment]
虽然词表大小有变化，但主要是控制字符的变化。我这里测试7b无需改变tiktoken文件，你是否对其他地方进行了修改？如有需要，可以在这里`https://huggingface.co/Qwen/Qwen2-7B-Instruct/tree/main`找到tokenizer相关文件，并自行转换成tiktoken形式。

**Comment by virtual1126** [comment]
发现是GPU环境的问题。RTX3060，CUDA 12.1，用`make -B build -DGGML_CUBLAS=ON && cmake --build build -j`这个命令编译，没有报错，但无法使用7B、1.5B转换出来的ggml文件，报错unknown token: 152063（运行7B时）

用CPU方式编译，使用附带的qwen.tiktoken就可以正常工作。
